#!/usr/bin/env python3
"""Convert an 8x16 BDF font (Spleen) into a C glyph table for ASCII 0-127."""
import sys
src, dst = sys.argv[1], sys.argv[2]
glyphs = {}
lines = open(src, encoding='latin1').read().splitlines()
i = 0
fbb = None
while i < len(lines):
    l = lines[i]
    if l.startswith('FONTBOUNDINGBOX'):
        fbb = list(map(int, l.split()[1:]))
    if l.startswith('STARTCHAR'):
        enc = None; bbx = None; bm = []
        while not lines[i].startswith('ENDCHAR'):
            t = lines[i]
            if t.startswith('ENCODING'): enc = int(t.split()[1])
            if t.startswith('BBX'): bbx = list(map(int, t.split()[1:]))
            if t == 'BITMAP':
                i += 1
                while not lines[i].startswith('ENDCHAR'):
                    bm.append(int(lines[i], 16)); i += 1
                break
            i += 1
        if enc is not None and enc < 256:
            w, h, xo, yo = bbx
            fw, fh, fxo, fyo = fbb
            rows = [0] * fh
            top = fh - (yo - fyo) - h
            for r, v in enumerate(bm):
                if 0 <= top + r < fh:
                    rows[top + r] = (v >> max(0, (8 * ((w + 7) // 8)) - 8)) >> xo if xo >= 0 else v
            glyphs[enc] = rows
    i += 1
# ---- front-panel glyphs (0x80-0x96), drawn here -------------------------
def cells_from(bitmap, w_cells, h_cells):
    """bitmap: list of rows (strings of '#'/'.') -> list of glyphs row-major."""
    out = []
    for cy in range(h_cells):
        for cx in range(w_cells):
            g = []
            for y in range(16):
                row = bitmap[cy * 16 + y][cx * 8:(cx + 1) * 8]
                g.append(sum(0x80 >> i for i, ch in enumerate(row) if ch == '#'))
            out.append(g)
    return out

def lamp(level):
    rows = []
    for y in range(16):
        r = ''
        for x in range(16):
            d = ((x - 7.5) ** 2 + (y - 7.5) ** 2) ** 0.5
            ring = 5.2 <= d <= 6.2
            fill = {0: False, 1: d <= 2.3, 2: d <= 4.2, 3: d <= 6.2}[level]
            r += '#' if (ring or fill) else '.'
        rows.append(r)
    return cells_from(rows, 2, 1)

def switch(up):
    rows = []
    for y in range(32):
        r = ''
        for x in range(16):
            hinge = y in (15, 16) and 1 <= x <= 14
            if up:
                paddle = 2 <= y <= 15 and 3 <= x <= 12
                edge = paddle and (x in (3, 12) or y == 2)
                body = paddle and (x + y) % 2 == 0      # stippled face
            else:
                paddle = 16 <= y <= 29 and 3 <= x <= 12
                edge = paddle and (x in (3, 12) or y == 29)
                body = paddle and (x + y) % 2 == 0
            r += '#' if (hinge or edge or body) else '.'
        rows.append(r)
    return cells_from(rows, 2, 2)

def box(kind):
    g = [0] * 16
    for y in range(16):
        v = 0
        if kind in ('-', 'tl', 'tr', 'bl', 'br') and y in (7, 8):
            v |= {'-': 0xff, 'tl': 0x1f, 'tr': 0xf8, 'bl': 0x1f, 'br': 0xf8}[kind]
        if kind == '|' or (kind in ('tl', 'tr') and y >= 7) or (kind in ('bl', 'br') and y <= 8):
            v |= 0x18
        g[y] = v
    return g

tri = []
for y in range(16):
    h = 6 - abs(y - 7.5) if 2 <= y <= 13 else -1
    tri.append(sum(0x80 >> i for i in range(8) if 0 < i + 1 <= h + 0.5 and i >= 1) if h > 0 else 0)

extra = {}
code = 0x80
for lv in range(4):
    for g in lamp(lv): extra[code] = g; code += 1
for up in (True, False):
    for g in switch(up): extra[code] = g; code += 1
extra[0x90] = tri
for i, k in enumerate(['-', '|', 'tl', 'tr', 'bl', 'br']):
    extra[0x91 + i] = box(k)

with open(dst, 'w') as f:
    f.write('/* Generated by tools/bdf2c.py.  0x00-0x7F: Spleen 8x16 (c) Frederic Cambus,\n'
            ' * BSD 2-Clause licence.  0x80-0x96: front-panel lamps, switches and frame. */\n')
    f.write('#include <stdint.h>\nconst uint8_t font8x16[256][16] = {\n')
    for c in range(256):
        rows = glyphs.get(c, [0] * 16) if c < 128 else extra.get(c, [0] * 16)
        f.write('  {' + ','.join('0x%02x' % r for r in rows) + '}, /* %d */\n' % c)
    f.write('};\n')
print(len(glyphs), 'glyphs')
